### ISSUE TITLE
조회수 급상승 질문 GET API 500에러

### ISSUE THREAD

**Issue by MayOwall** [boostcampwm2023/web04-ALGOCEAN#235]
### 버그 내용

조회수 급상승 질문 GET API에 대한 응답이 500으로 내려옴

<img width="681" alt="image" src="https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/97934878/17f91c5f-c235-4629-8fbe-49c35ceda29b">

### 버그 재현 방법

- https://algocean.site/api/questions/trending 으로 GET 요청

### 정상 동작시 예상되는 모습

- 200 status와 함께 조회수 급상승 질문에 대한 데이터 응답
- 404 status와 함께 급상승 질문이 없다고 응답

### 관련 PR

#172

**Comment by perArdua** [comment]
이거는 백엔드 쪽에서 라우팅이 잘못돼서 그래요
이 부분 수정했습니다.

**Comment by MayOwall** [comment]
갓벽 완벽 태호쿤 👍
@perArdua
