### ISSUE TITLE
소셜 로그인시 화면이 다운되는 에러

### ISSUE THREAD

**Issue by MayOwall** [boostcampwm2023/web04-ALGOCEAN#290]
**버그 내용*
소셜 로그인시 화면이 먹힘.

**재현 방법**
소셜 로그인 시도

**스크린샷**
<img width="806" alt="image" src="https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/97934878/dabf51a6-cb76-4d4a-95ce-93e5880aeb5b">

**ETC**
아마 전역 유저 정보를 저장하는 과정에서 문제가 있었으리라 추측

**Comment by MayOwall** [comment]
`/users/me`에서 400에러가 내려오네요.
새로 발급받은 access token을 잘 넣고 있는 것까지 확인 완료했습니다.
제가 잘못 전달한 값이나 빠트린 값이 있을까요? 잘 모르겠어서 여쭤봅니다 ㅜㅠ
@seungy0 @perArdua 

### 응답 결과

![image](https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/97934878/b780bf5a-6d51-4d2c-978c-ffd0a12dfd27)

### Request Headers

![image](https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/97934878/47e78707-7f16-4b83-8576-1dcc6af80fd5)

### Response Headers

![image](https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/97934878/2d850774-8cee-4ff5-8078-b3b46f7f352f)

**Comment by perArdua** [comment]
![image](https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/70432496/b67e7400-2027-40c2-b7b4-11408a951142)

저는 잘 되는 것 같은데 뭐가 문제일까요
