### ISSUE TITLE
CORS 에러

### ISSUE THREAD

**Issue by perArdua** [boostcampwm2023/web04-ALGOCEAN#62]
**버그 내용**

리액트 로컬 환경에서 배포된 서버로 요청을 보낼 때 CORS 오류 발생함

<br/>

**재현 방법**
1. 로컬 환경에서 리액트 실행
2. 브라우저를 통해 localhost:5173 접속 (접속하면 서버로 api를 요청하도록 했음)
3. 네트워크 탭을 통해 에러 확인

**정상 작동했다면 일어났어야 하는 일**
요청한 api에 대한 응답이 돌아와야 함

**스크린샷**
![cors](https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/70432496/de755bd1-7059-40c8-8db1-56a421dec0e9)

**클라이언트 Request 정보**

<img src='https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/97934878/f0a42c17-2b4a-4d4d-a277-9ed582d00ef3' width=500 />

- host : 223.130.147.11
- origin : http://localhost:5173

<br/>

**ETC**
태호: 해결하는 코드는 아는데 배포된 서버 어디에서 수정을 해야하는지 모르겠음 -> 해결방법을 모르겠음 -> 살려주세요!!!
태호: FE, BE 둘 중 한 곳에서 해결할 수 있을 것으로 보임 어느 곳에서 해결할지 이유를 찾아볼 것

<br/>

**Comment by MayOwall** [comment]
nest 공식 문서에도 CORS 허락에 대한 이야기가 나와 있네요!
[CORS | NestJS](https://docs.nestjs.com/security/cors)

@perArdua

**Comment by seungy0** [comment]
네 origin이 다르니까 CORS 문제가 생길 수 밖에 없겠네요
