### ISSUE TITLE
문서 에디터 채택

### ISSUE THREAD

**Issue by perArdua** [boostcampwm2023/web04-ALGOCEAN#9]
**기능 소개**
문서 에디터 라이브러리 결정

**TODO**
- [x] 문서 에디터 종류 비교
- [x] 문서 에디터 결정

**ETC**

**Comment by MayOwall** [comment]
### react-draft-wysiwyg

> [공식 레포지토리](https://github.com/jpuri/react-draft-wysiwyg)

**`장점`**

- 압도적 유저 수 (npm 기준 주 18만회 다운로드)
- 풍부한 API 및 플러그인 시스템

**`단점`**

- 거대한 번들 크기
- 조금 투박한 디자인
